template:
# Current Estimated Electricity Price
  - sensor:
    - name: forecast_monthly_electricity_compensation_pricenow
      unit_of_measurement: NOK/kWh
      state: >
        {{ '{:.2f}'.format(((states('sensor.nordpool_kwh_bergen_nok_3_095_025') | float) - (states('sensor.forecast_monthly_electricity_compensation_mean') | float)) | round(2)) }}
      attributes:
        price: >
          {{ ((states('sensor.nordpool_kwh_bergen_nok_3_095_025') | float) - (states('sensor.forecast_monthly_electricity_compensation_mean') | float)) | round(3) }}
      icon: >
          {% if (states('sensor.nordpool_kwh_bergen_nok_3_095_025') | float) - (states('sensor.forecast_monthly_electricity_compensation_mean') | float) > 0 %}
            mdi:cash-minus
          {% else %}
            mdi:cash-plus
          {% endif %}



# Includes
rest: !include rest.yaml
