template:
# Current Estimated Electricity Price
  - sensor:
    - name: forecast_monthly_electricity_compensation_pricenow
      unit_of_measurement: NOK/kWh
      state: >
        {{ (states('sensor.electricity_price_minadresse') | float) - (states('sensor.forecast_monthly_electricity_compensation_mean') | float)}}
      icon: >
          {% if (states('sensor.electricity_price_haukedalsveien_46') | float) - (states('sensor.forecast_monthly_electricity_compensation_mean') | float) > 0 %}
            mdi:cash-plus
          {% else %}
            mdi:cash-minus
          {% endif %}


# Includes
rest: !include rest.yaml
